const ActionTypes = {

	FETCH_CONSUMER_PLAN:"FETCH_CONSUMER_PLAN",
	GET_CONSUMER_PLAN:"GET_CONSUMER_PLAN",
	FETCH_CONSUMER_PLAN_FAILED:"FETCH_CONSUMER_PLAN_FAILED"
	
}; 

export default ActionTypes;
